repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: ^(app/|tests/)
        stages: [push]
        args: [
          '--experimental-string-processing',
          '--max-line-length=120',
        ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        include: ^(app/|tests/)
        exclude: '.*/migrations/.*'
        stages: [push]
        args: [
          '--line-length=110',
          '--multi-line=3',
          '--force-grid-wrap=0',
          '--trailing-comma',
          '--use-parentheses',
          '--ensure-newline-before-comments',
        ]
      - id: pylama
        name: pylama
        entry: pylama
        language: system
        types: [ python ]
        files: ^(app/|tests/)
        stages: [push]